version: 2.1


orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Build
          command: npm run build --if-present
      - run:
          name: Run Tests
          command: npm test || echo "No tests found, continuing..."

  deploy:
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true 

workflows:
  version: 2
  university_pipeline:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main 